// src/containers/Getaway/Getaway.jsx
import React from "react";
import "./Getaway.scss";

const Getaway = () => {
  return (
    <section class="getaway section-padding">
      <div class="getaway__container">
        <div class="wrapper">
          <h2 class="getaway__text">
            The Guest House is the perfect weekend getaway cabin.
          </h2>
        </div>
      </div>
    </section>
  );
};

export default Getaway;

// src/components/Getaway.vue
<template>
  <section class="getaway section-padding">
    <div class="getaway__container">
      <div class="wrapper">
        <h2 class="getaway__text">{{text}}</h2>
      </div>
    </div>
  </section>
</template>

<script>

export default {
  name: 'Getaway',
  props: [
    'text'
  ]
}
</script>
